services:
  backend:
    build:
      context: ./backend
    container_name: django-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - db
    environment:
      - DB_NAME=hcc-database
      - DB_USER=amostradin
      - DB_PASSWORD=humm
      - DB_HOST=db
      - DB_PORT=3306

  frontend:
    build:
      context: ./frontend
    container_name: vue-frontend
    ports:
      - "80:80"
    volumes:
      - ./frontend:/app

  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: eugostoassim
      MYSQL_DATABASE: hcc-database
      MYSQL_USER: amostradin
      MYSQL_PASSWORD: humm
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
