# Generated by Django 5.1 on 2024-09-07 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_devices_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='status',
            field=models.CharField(default='---', max_length=30),
            preserve_default=False,
        ),
    ]
